<?php

/**
 * @file
 * Provides a block displaying prayer times for the visitor's location
 */
function astrooda_magic_enable() {
  $astrooda_settings = variable_get('astrooda_settings');
  $astrooda_settings['instruments']['magic']['enabled'] = true;
  variable_set ( 'astrooda_settings', $astrooda_settings );
}

function astrooda_magic_disable() {
  $astrooda_settings = variable_get('astrooda_settings');
  $astrooda_settings['instruments']['magic']['enabled'] = false;
  variable_set ( 'astrooda_settings', $astrooda_settings );
}

function astrooda_magic_init() {
}

/**
 * Implements hook_help().
 */
function astrooda_magic_help($path, $arg) {
  $output = '';
  switch ($path) {
    case 'admin/help#astrooda_magic' :
      $output = '<p>';
      $output .= t ( "Astrooda Magic." );
      $output .= '</p>';
      break;
  }
  return $output;
}

/**
 * Implementation of hook_permission().
 */

function astrooda_magic_permission() {
  return array (
      'administer astrooda magic' => array (
          'description' => t ( 'Administer Astrooda Magic' ),
          'title' => t ( 'Administer Astrooda Magic' ),
          'restrict access' => TRUE
      ),
      'access astrooda magic' => array (
          'description' => t ( 'Access Astrooda Magic' ),
          'title' => t ( 'Access Astrooda Magic' ),
          'restrict access' => TRUE
      )
  );
}

/**
 * Menu callback.
 * Prints a listing of active nodes on the site.
 */
function astrooda_magic_menu() {
  $items = array ();
  
  $items ['admin/config/astrooda/magic'] = array (
      'title' => 'Administer Astrooda Magic',
      'page callback' => 'drupal_get_form',
      'page arguments' => array (
          'astrooda_magic_admin_settings'
      ),
      'description' => 'Edit Astrooda Magic settings.',
      'file' => 'astrooda_magic.admin.inc'
  );
  // 'weight' => -10,
  
  return $items;
}

