<?php

function mmoda_node_update($node)
{
  error_log("updated node\n" . print_r($node->id(), true));
  //   error_log("updated node\n");
}

function mmoda_install($is_syncing)
{
  \Drupal::configFactory()->getEditable('system.site')
    ->set('page.front', '/mmoda')
    ->save();
}

function mmoda_uninstall($is_syncing)
{
  \Drupal::configFactory()->getEditable('system.site')
    ->set('page.front', '/node')
    ->save();
}

/**
 * Implements hook_theme().
 */
function mmoda_theme($existing, $type, $theme, $path)
{
  return [
    'mmoda_common_form' => [
      'render element' => 'form'
    ],
    'mmoda_name_resolve_form' => [
      'render element' => 'form'
    ],
    'mmoda' => [
      'variables' => [
        'instruments' => [],
        'name_resolve_form' => 'Name resolver form',
        'common_form' => 'Common form'
      ]
    ]
  ];
}

/**
 * Implements hook_page_attachments().
 */
function mmoda_page_attachments(array &$attachments)
{
  // Unconditionally attach an asset to the page.
//   dpm('attaching lib');
//   $attachments['#attached']['library'][] = 'mmoda/bootstrap_form_validatorrrr';
}