<?php

/**
 * @file
 * Provides a block displaying prayer times for the visitor's location
 */
function mmoda_spi_acs_enable() {
  $instrument = mmoda_spi_acs_instrument_info()['name'];
  _mmodaa_instrument_enable($instrument);
}

function mmoda_spi_acs_disable() {
  $instrument = mmoda_spi_acs_instrument_info()['name'];
  _mmodaa_instrument_disable($instrument);
}

function mmoda_spi_acs_init() {
}

/**
 * Implements hook_help().
 */
function mmoda_spi_acs_help($path, $arg) {
  $output = '';
  switch ($path) {
    case 'admin/help#mmoda_spi_acs' :
      $output = '<p>';
      $output .= t ( "MMODA SPI-ACS." );
      $output .= '</p>';
      break;
  }
  return $output;
}

/**
 * Implementation of hook_permission().
 */

function mmoda_spi_acs_permission() {
  return array (
      'administer mmoda spi_acs' => array (
          'description' => t ( 'Administer MMODA SPI-ACS' ),
          'title' => t ( 'Administer MMODA SPI-ACS' ),
          'restrict access' => TRUE
      ),
      'access mmoda spi_acs' => array (
          'description' => t ( 'Access MMODA SPI-ACS' ),
          'title' => t ( 'Access MMODA SPI-ACS' ),
          'restrict access' => TRUE
      )
  );
}

/**
 * Menu callback.
 * Prints a listing of active nodes on the site.
 */
function mmoda_spi_acs_menu() {
  $items = array ();

  $items ['admin/config/mmoda/spi_acs'] = array (
      'title' => 'Administer MMODA SPI-ACS',
      'page callback' => 'drupal_get_form',
      'page arguments' => array (
          'mmoda_spi_acs_admin_settings'
      ),
      'description' => 'Edit MMODA SPI-ACS settings.',
      'file' => 'mmoda_spi_acs.admin.inc'
  );
  // 'weight' => -10,

  return $items;
}

