<?php

/**
 * @file
 * Provides a block displaying prayer times for the visitor's location
 */
function astrooda_gw_enable() {
  $instrument = mmoda_gw_instrument_info()['name'];
  _mmodaa_instrument_enable($instrument);
}

function astrooda_gw_disable() {
  $instrument = mmoda_gw_instrument_info()['name'];
  _mmodaa_instrument_disable($instrument);
}

function astrooda_gw_init() {
}

/**
 * Implements hook_help().
 */
function astrooda_gw_help($path, $arg) {
  $output = '';
  switch ($path) {
    case 'admin/help#astrooda_gw' :
      $output = '<p>';
      $output .= t ( "Astrooda GW." );
      $output .= '</p>';
      break;
  }
  return $output;
}

/**
 * Implementation of hook_permission().
 */

function astrooda_gw_permission() {
  return array (
      'administer astrooda gw' => array (
          'description' => t ( 'Administer Astrooda GW' ),
          'title' => t ( 'Administer Astrooda GW' ),
          'restrict access' => TRUE
      ),
      'access astrooda gw' => array (
          'description' => t ( 'Access Astrooda GW' ),
          'title' => t ( 'Access Astrooda GW' ),
          'restrict access' => TRUE
      )
  );
}

/**
 * Menu callback.
 * Prints a listing of active nodes on the site.
 */
function astrooda_gw_menu() {
  $items = array ();
  
  $items ['admin/config/astrooda/gw'] = array (
      'title' => 'Administer Astrooda GW',
      'page callback' => 'drupal_get_form',
      'page arguments' => array (
          'astrooda_gw_admin_settings'
      ),
      'description' => 'Edit Astrooda GW settings.',
      'file' => 'astrooda_gw.admin.inc'
  );
  // 'weight' => -10,
  
  return $items;
}

