<?php

/**
 * @file
 * Provides a block displaying prayer times for the visitor's location
 */
function astrooda_legacysurvey_enable() {
  $instrument = mmoda_legacysurvey_instrument_info()['name'];
  _mmodaa_instrument_enable($instrument);
}

function astrooda_legacysurvey_disable() {
  $instrument = mmoda_legacysurvey_instrument_info()['name'];
  _mmodaa_instrument_disable($instrument);
}

function astrooda_legacysurvey_init() {
}

/**
 * Implements hook_help().
 */
function astrooda_legacysurvey_help($path, $arg) {
  $output = '';
  switch ($path) {
    case 'admin/help#astrooda_legacysurvey' :
      $output = '<p>';
      $output .= t ( "Astrooda LegacySurvey." );
      $output .= '</p>';
      break;
  }
  return $output;
}

/**
 * Implementation of hook_permission().
 */

function astrooda_legacysurvey_permission() {
  return array (
      'administer astrooda legacysurvey' => array (
          'description' => t ( 'Administer Astrooda LegacySurvey' ),
          'title' => t ( 'Administer Astrooda LegacySurvey' ),
          'restrict access' => TRUE
      ),
      'access astrooda legacysurvey' => array (
          'description' => t ( 'Access Astrooda LegacySurvey' ),
          'title' => t ( 'Access Astrooda LegacySurvey' ),
          'restrict access' => TRUE
      )
  );
}

/**
 * Menu callback.
 * Prints a listing of active nodes on the site.
 */
function astrooda_legacysurvey_menu() {
  $items = array ();
  
  $items ['admin/config/astrooda/legacysurvey'] = array (
      'title' => 'Administer Astrooda LegacySurvey',
      'page callback' => 'drupal_get_form',
      'page arguments' => array (
          'astrooda_legacysurvey_admin_settings'
      ),
      'description' => 'Edit Astrooda LegacySurvey settings.',
      'file' => 'astrooda_legacysurvey.admin.inc'
  );
  // 'weight' => -10,
  
  return $items;
}

