<?php

/**
 * @file
 * Provides a block displaying prayer times for the visitor's location
 */


function astrooda_isgri_enable() {
  $astrooda_settings = variable_get('astrooda_settings');
  $astrooda_settings['instruments']['isgri']['enabled'] = true;
  variable_set ( 'astrooda_settings', $astrooda_settings );
}

function astrooda_isgri_disable() {
  $astrooda_settings = variable_get('astrooda_settings');
  $astrooda_settings['instruments']['isgri']['enabled'] = false;
  variable_set ( 'astrooda_settings', $astrooda_settings );
}

function astrooda_isgri_init() {
}

/**
 * Implements hook_help().
 */
function astrooda_isgri_help($path, $arg) {
  $output = '';
  switch ($path) {
    case 'admin/help#astrooda_isgri' :
      $output = '<p>';
      $output .= t ( "Astrooda ISGRI." );
      $output .= '</p>';
      break;
  }
  return $output;
}

/**
 * Implementation of hook_permission().
 */

function astrooda_isgri_permission() {
  return array (
      'administer astrooda isgri' => array (
          'description' => t ( 'Administer Astrooda ISGRI' ),
          'title' => t ( 'Administer Astrooda ISGRI' ),
          'restrict access' => TRUE
      ),
      'access astrooda isgri' => array (
          'description' => t ( 'Access Astrooda ISGRI' ),
          'title' => t ( 'Access Astrooda ISGRI' ),
          'restrict access' => TRUE
      )
  );
}

/**
 * Menu callback.
 * Prints a listing of active nodes on the site.
 */
function astrooda_isgri_menu() {
  $items = array ();
  
  $items ['admin/config/astrooda/isgri'] = array (
      'title' => 'Administer Astrooda ISGRI',
      'page callback' => 'drupal_get_form',
      'page arguments' => array (
          'astrooda_isgri_admin_settings'
      ),
      'description' => 'Edit Astrooda ISGRI settings.',
      'file' => 'astrooda_isgri.admin.inc'
  );
  // 'weight' => -10,
  
  return $items;
}

