<?php

/**
 *
 * @file
 * Provides a block displaying prayer times for the visitor's location
 */
function mmoda_gallery_enable()
{
  $instrument = mmoda_gallery_instrument_info()['name'];
  _mmodaa_instrument_enable($instrument);
}

function mmoda_gallery_disable()
{
  $instrument = mmoda_gallery_instrument_info()['name'];
  _mmodaa_instrument_disable($instrument);
}

function mmoda_gallery_init()
{}

/**
 * Implements hook_help().
 */
function mmoda_gallery_help($path, $arg)
{
  $output = '';
  switch ($path) {
    case 'admin/help#mmoda_gallery':
      $output = '<p>';
      $output .= t("MMODA Gallery.");
      $output .= '</p>';
      break;
  }
  return $output;
}

/**
 * Implementation of hook_permission().
 */
function mmoda_gallery_permission()
{
  return array(
    'administer mmoda gallery' => array(
      'description' => t('Administer MMODA Gallery'),
      'title' => t('Administer MMODA Gallery'),
      'restrict access' => TRUE
    ),
    'access mmoda gallery' => array(
      'description' => t('Access MMODA Gallery'),
      'title' => t('Access MMODA Gallery'),
      'restrict access' => TRUE
    )
  );
}

/**
 * Menu callback.
 * Prints a listing of active nodes on the site.
 */
function mmoda_gallery_menu()
{
  $items = array();

  $items['admin/config/mmoda/gallery'] = array(
    'title' => 'Administer MMODA Gallery',
    'page callback' => 'drupal_get_form',
    'page arguments' => array(
      'mmoda_gallery_admin_settings'
    ),
    'description' => 'Edit MMODA Gallery settings.',
    'file' => 'mmoda_gallery.admin.inc'
  );
  // 'weight' => -10,
  $items['gallery_query'] = array(
    'page callback' => 'mmoda_gallery_get_products_ajax',
    'type' => MENU_CALLBACK,
    'access arguments' => array(
      'access content'
    )
  );

  return $items;
}

/**
 * Callback to return JSON encoded image for given nid.
 */
function mmoda_gallery_get_products_ajax()
{
  $query_params= $_POST;
  $url = "https://www.astro.unige.ch/mmoda/gallery/astro_entities/all_sources?_format=hal_json&src_name=Mrk+421";
  $ourl = 'https://cdcidev.mtmco.net/mmoda/galleryd/node/5694/preview';
//   $ourl = 'https://cdciweb02.isdc.unige.ch/mmoda/galleryd/node/5694/preview';
  $request = drupal_http_request($url);
  $json_response = drupal_json_decode($request->data);
  //drupal_add_http_header('X-Frame-Options', 'allow-from https://www.astro.unige.ch/', FALSE);
  drupal_json_output(array(
    'exit_status' => array ('status' => 0),
    'query_status' => 'done',
    'params' => $query_params,
    'json_response' => $json_response,
    'htmlResponse' => '<iframe src="'.$ourl.'" title="MMODA Gallerys" class="mmoda-gallery-iframe-mod"></iframe>'
  ));
}
