<?php

/**
 * @file
 * Provides a block displaying prayer times for the visitor's location
 */
function mmoda_antares_enable() {
  $instrument = mmoda_antares_instrument_info()['name'];
  _mmodaa_instrument_enable($instrument);
}

function mmoda_antares_disable() {
  $instrument = mmoda_antares_instrument_info()['name'];
  _mmodaa_instrument_disable($instrument);
}

function mmoda_antares_init() {
}

/**
 * Implements hook_help().
 */
function mmoda_antares_help($path, $arg) {
  $output = '';
  switch ($path) {
    case 'admin/help#mmoda_antares' :
      $output = '<p>';
      $output .= t ( "MMODA Antares." );
      $output .= '</p>';
      break;
  }
  return $output;
}

/**
 * Implementation of hook_permission().
 */

function mmoda_antares_permission() {
  return array (
      'administer mmoda antares' => array (
          'description' => t ( 'Administer MMODA Antares' ),
          'title' => t ( 'Administer MMODA Antares' ),
          'restrict access' => TRUE
      ),
      'access mmoda antares' => array (
          'description' => t ( 'Access MMODA Antares' ),
          'title' => t ( 'Access MMODA Antares' ),
          'restrict access' => TRUE
      )
  );
}

/**
 * Menu callback.
 * Prints a listing of active nodes on the site.
 */
function mmoda_antares_menu() {
  $items = array ();

  $items ['admin/config/mmoda/antares'] = array (
      'title' => 'Administer MMODA Antares',
      'page callback' => 'drupal_get_form',
      'page arguments' => array (
          'mmoda_antares_admin_settings'
      ),
      'description' => 'Edit MMODA Antares settings.',
      'file' => 'mmoda_antares.admin.inc'
  );
  // 'weight' => -10,

  return $items;
}

