<?php

/**
 * Implements hook_theme().
 */
function mmoda_grb_detection_theme($existing, $type, $theme, $path)
{
  return [
  'mmoda_grb_detection_form'=> [
    'render element' => 'form',
  ]
];

}

function mmoda_grb_detection_install($is_syncing)
{
  mmoda_help_pages_book_publish('mmoda_grb_detection');
}

function mmoda_grb_detection_uninstall($is_syncing)
{
  mmoda_help_pages_book_unpublish('mmoda_grb_detection');
}
