<?php

/**
 * @file
 * Provides a block displaying prayer times for the visitor's location
 */

function mmoda_magic_enable() {
  $instrument = mmoda_magic_instrument_info()['name'];
  _mmodaa_instrument_enable($instrument);
}

function mmoda_magic_disable() {
  $instrument = mmoda_magic_instrument_info()['name'];
  _mmodaa_instrument_disable($instrument);
}


function mmoda_magic_init() {
}

/**
 * Implements hook_help().
 */
function mmoda_magic_help($path, $arg) {
  $output = '';
  switch ($path) {
    case 'admin/help#mmoda_magic' :
      $output = '<p>';
      $output .= t ( "MMODA Magic." );
      $output .= '</p>';
      break;
  }
  return $output;
}

/**
 * Implementation of hook_permission().
 */

function mmoda_magic_permission() {
  return array (
      'administer mmoda magic' => array (
          'description' => t ( 'Administer MMODA Magic' ),
          'title' => t ( 'Administer MMODA Magic' ),
          'restrict access' => TRUE
      ),
      'access mmoda magic' => array (
          'description' => t ( 'Access MMODA Magic' ),
          'title' => t ( 'Access MMODA Magic' ),
          'restrict access' => TRUE
      )
  );
}

/**
 * Menu callback.
 * Prints a listing of active nodes on the site.
 */
function mmoda_magic_menu() {
  $items = array ();

  $items ['admin/config/mmoda/magic'] = array (
      'title' => 'Administer MMODA Magic',
      'page callback' => 'drupal_get_form',
      'page arguments' => array (
          'mmoda_magic_admin_settings'
      ),
      'description' => 'Edit MMODA Magic settings.',
      'file' => 'mmoda_magic.admin.inc'
  );
  // 'weight' => -10,

  return $items;
}

