<?php

/**
 * @file
 * Provides a block displaying prayer times for the visitor's location
 */
function astrooda_antares_enable() {
  $astrooda_settings = variable_get('astrooda_settings');
  $astrooda_settings['instruments']['antares']['enabled'] = true;
  variable_set ( 'astrooda_settings', $astrooda_settings );
}

function astrooda_antares_disable() {
  $astrooda_settings = variable_get('astrooda_settings');
  $astrooda_settings['instruments']['antares']['enabled'] = false;
  variable_set ( 'astrooda_settings', $astrooda_settings );
}

function astrooda_antares_init() {
}

/**
 * Implements hook_help().
 */
function astrooda_antares_help($path, $arg) {
  $output = '';
  switch ($path) {
    case 'admin/help#astrooda_antares' :
      $output = '<p>';
      $output .= t ( "Astrooda Antares." );
      $output .= '</p>';
      break;
  }
  return $output;
}

/**
 * Implementation of hook_permission().
 */

function astrooda_antares_permission() {
  return array (
      'administer astrooda antares' => array (
          'description' => t ( 'Administer Astrooda Antares' ),
          'title' => t ( 'Administer Astrooda Antares' ),
          'restrict access' => TRUE
      ),
      'access astrooda antares' => array (
          'description' => t ( 'Access Astrooda Antares' ),
          'title' => t ( 'Access Astrooda Antares' ),
          'restrict access' => TRUE
      )
  );
}

/**
 * Menu callback.
 * Prints a listing of active nodes on the site.
 */
function astrooda_antares_menu() {
  $items = array ();
  
  $items ['admin/config/astrooda/antares'] = array (
      'title' => 'Administer Astrooda Antares',
      'page callback' => 'drupal_get_form',
      'page arguments' => array (
          'astrooda_antares_admin_settings'
      ),
      'description' => 'Edit Astrooda Antares settings.',
      'file' => 'astrooda_antares.admin.inc'
  );
  // 'weight' => -10,
  
  return $items;
}

