<?php

/**
 * @file
 * Provides a block displaying prayer times for the visitor's location
 */
function astrooda_jemx_enable() {
  $astrooda_settings = variable_get('astrooda_settings');
  $astrooda_settings['instruments']['jemx']['enabled'] = true;
  variable_set ( 'astrooda_settings', $astrooda_settings );
}

function astrooda_jemx_disable() {
  $astrooda_settings = variable_get('astrooda_settings');
  $astrooda_settings['instruments']['jemx']['enabled'] = false;
  variable_set ( 'astrooda_settings', $astrooda_settings );
}

function astrooda_jemx_init() {
}

/**
 * Implements hook_help().
 */
function astrooda_jemx_help($path, $arg) {
  $output = '';
  switch ($path) {
    case 'admin/help#astrooda_jemx' :
      $output = '<p>';
      $output .= t ( "Astrooda JEM-X." );
      $output .= '</p>';
      break;
  }
  return $output;
}

/**
 * Implementation of hook_permission().
 */

function astrooda_jemx_permission() {
  return array (
      'administer astrooda jemx' => array (
          'description' => t ( 'Administer Astrooda JEM-X' ),
          'title' => t ( 'Administer Astrooda JEM-X' ),
          'restrict access' => TRUE
      ),
      'access astrooda jemx' => array (
          'description' => t ( 'Access Astrooda JEM-X' ),
          'title' => t ( 'Access Astrooda JEM-X' ),
          'restrict access' => TRUE
      )
  );
}

/**
 * Menu callback.
 * Prints a listing of active nodes on the site.
 */
function astrooda_jemx_menu() {
  $items = array ();
  
  $items ['admin/config/astrooda/jemx'] = array (
      'title' => 'Administer Astrooda JEM-X',
      'page callback' => 'drupal_get_form',
      'page arguments' => array (
          'astrooda_jemx_admin_settings'
      ),
      'description' => 'Edit Astrooda JEM-X settings.',
      'file' => 'astrooda_jemx.admin.inc'
  );
  // 'weight' => -10,
  
  return $items;
}

