<?php

/**
 * @file
 * Provides a block displaying prayer times for the visitor's location
 */


function mmoda_isgri_enable() {
  $instrument = mmoda_isgri_instrument_info()['name'];
  _mmodaa_instrument_enable($instrument);
}

function mmoda_isgri_disable() {
  $instrument = mmoda_isgri_instrument_info()['name'];
  _mmodaa_instrument_disable($instrument);
}

function mmoda_isgri_init() {
}

/**
 * Implements hook_help().
 */
function mmoda_isgri_help($path, $arg) {
  $output = '';
  switch ($path) {
    case 'admin/help#mmoda_isgri' :
      $output = '<p>';
      $output .= t ( "MMODA ISGRI." );
      $output .= '</p>';
      break;
  }
  return $output;
}

/**
 * Implementation of hook_permission().
 */

function mmoda_isgri_permission() {
  return array (
      'administer mmoda isgri' => array (
          'description' => t ( 'Administer MMODA ISGRI' ),
          'title' => t ( 'Administer MMODA ISGRI' ),
          'restrict access' => TRUE
      ),
      'access mmoda isgri' => array (
          'description' => t ( 'Access MMODA ISGRI' ),
          'title' => t ( 'Access MMODA ISGRI' ),
          'restrict access' => TRUE
      )
  );
}

/**
 * Menu callback.
 * Prints a listing of active nodes on the site.
 */
function mmoda_isgri_menu() {
  $items = array ();

  $items ['admin/config/mmoda/isgri'] = array (
      'title' => 'Administer MMODA ISGRI',
      'page callback' => 'drupal_get_form',
      'page arguments' => array (
          'mmoda_isgri_admin_settings'
      ),
      'description' => 'Edit MMODA ISGRI settings.',
      'file' => 'mmoda_isgri.admin.inc'
  );
  // 'weight' => -10,

  return $items;
}

