<?php

/**
 * @file
 * Provides a block displaying prayer times for the visitor's location
 */


function mmoda_euclid_enable() {
  $instrument = mmoda_euclid_instrument_info()['name'];
  _mmodaa_instrument_enable($instrument);
}

function mmoda_euclid_disable() {
  $instrument = mmoda_euclid_instrument_info()['name'];
  _mmodaa_instrument_disable($instrument);
}

function mmoda_euclid_init() {
}

/**
 * Implements hook_help().
 */
function mmoda_euclid_help($path, $arg) {
  $output = '';
  switch ($path) {
    case 'admin/help#mmoda_euclid' :
      $output = '<p>';
      $output .= t ( "MMODA Euclid." );
      $output .= '</p>';
      break;
  }
  return $output;
}

/**
 * Implementation of hook_permission().
 */

function mmoda_euclid_permission() {
  return array (
      'administer mmoda euclid' => array (
          'description' => t ( 'Administer MMODA Euclid' ),
          'title' => t ( 'Administer MMODA Euclid' ),
          'restrict access' => TRUE
      ),
      'access mmoda euclid' => array (
          'description' => t ( 'Access MMODA Euclid' ),
          'title' => t ( 'Access MMODA Euclid' ),
          'restrict access' => TRUE
      )
  );
}

/**
 * Menu callback.
 * Prints a listing of active nodes on the site.
 */
function mmoda_euclid_menu() {
  $items = array ();

  $items ['admin/config/mmoda/euclid'] = array (
      'title' => 'Administer MMODA Euclid',
      'page callback' => 'drupal_get_form',
      'page arguments' => array (
          'mmoda_euclid_admin_settings'
      ),
      'description' => 'Edit MMODA Euclid settings.',
      'file' => 'mmoda_euclid.admin.inc'
  );
  // 'weight' => -10,

  return $items;
}

