<?php

/**
 * @file
 * Provides a block displaying prayer times for the visitor's location
 */
function mmoda_multiproduct_init() {
}

/**
 * Implements hook_help().
 */
function mmoda_multiproduct_help($path, $arg) {
  $output = '';
  switch ($path) {
    case 'admin/help#mmoda_multiproduct' :
      $output = '<p>';
      $output .= t ( "MMODA Multi Product." );
      $output .= '</p>';
      break;
  }
  return $output;
}

/**
 * Implementation of hook_permission().
 */

function mmoda_multiproduct_permission() {
  return array (
      'administer mmoda multiproduct' => array (
          'description' => t ( 'Administer MMODA Multi Product' ),
          'title' => t ( 'Administer MMODA Multi Product' ),
          'restrict access' => TRUE
      ),
      'access mmoda multiproduct' => array (
          'description' => t ( 'Access MMODA Multi Product' ),
          'title' => t ( 'Access MMODA Multi Product' ),
          'restrict access' => TRUE
      )
  );
}

/**
 * Menu callback.
 * Prints a listing of active nodes on the site.
 */
function mmoda_multiproduct_menu() {
  $items = array ();
  
  $items ['admin/config/mmoda/multiproduct'] = array (
      'title' => 'Administer MMODA Multi Product',
      'page callback' => 'drupal_get_form',
      'page arguments' => array (
          'mmoda_multiproduct_admin_settings'
      ),
      'description' => 'Edit MMODA Multi Product settings.',
      'file' => 'mmoda_multiproduct.admin.inc'
  );
  // 'weight' => -10,
  
  return $items;
}

