<?php

/**
 * @file
 * Provides a block displaying prayer times for the visitor's location
 */

function mmoda_itest_enable() {
  $instrument = mmoda_itest_instrument_info()['name'];
  _mmodaa_instrument_enable($instrument);
}

function mmoda_itest_disable() {
  $instrument = mmoda_itest_instrument_info()['name'];
  _mmodaa_instrument_disable($instrument);
}

function mmoda_itest_init() {
}

/**
 * Implements hook_help().
 */
function mmoda_itest_help($path, $arg) {
  $output = '';
  switch ($path) {
    case 'admin/help#mmoda_itest' :
      $output = '<p>';
      $output .= t ( "MMODA Polar." );
      $output .= '</p>';
      break;
  }
  return $output;
}

/**
 * Implementation of hook_permission().
 */

function mmoda_itest_permission() {
  return array (
      'administer mmoda itest' => array (
          'description' => t ( 'Administer MMODA Polar' ),
          'title' => t ( 'Administer MMODA Polar' ),
          'restrict access' => TRUE
      ),
      'access mmoda itest' => array (
          'description' => t ( 'Access MMODA Polar' ),
          'title' => t ( 'Access MMODA Polar' ),
          'restrict access' => TRUE
      )
  );
}

/**
 * Menu callback.
 * Prints a listing of active nodes on the site.
 */
function mmoda_itest_menu() {
  $items = array ();

  $items ['admin/config/mmoda/itest'] = array (
      'title' => 'Administer MMODA Polar',
      'page callback' => 'drupal_get_form',
      'page arguments' => array (
          'mmoda_itest_admin_settings'
      ),
      'description' => 'Edit MMODA Polar settings.',
      'file' => 'mmoda_itest.admin.inc'
  );
  // 'weight' => -10,

  return $items;
}

