<?php

/**
 * @file
 * Provides a block displaying prayer times for the visitor's location
 */
function astrooda_multiproduct_init() {
}

/**
 * Implements hook_help().
 */
function astrooda_multiproduct_help($path, $arg) {
  $output = '';
  switch ($path) {
    case 'admin/help#astrooda_multiproduct' :
      $output = '<p>';
      $output .= t ( "Astrooda Multi Product." );
      $output .= '</p>';
      break;
  }
  return $output;
}

/**
 * Implementation of hook_permission().
 */

function astrooda_multiproduct_permission() {
  return array (
      'administer astrooda multiproduct' => array (
          'description' => t ( 'Administer Astrooda Multi Product' ),
          'title' => t ( 'Administer Astrooda Multi Product' ),
          'restrict access' => TRUE
      ),
      'access astrooda multiproduct' => array (
          'description' => t ( 'Access Astrooda Multi Product' ),
          'title' => t ( 'Access Astrooda Multi Product' ),
          'restrict access' => TRUE
      )
  );
}

/**
 * Menu callback.
 * Prints a listing of active nodes on the site.
 */
function astrooda_multiproduct_menu() {
  $items = array ();
  
  $items ['admin/config/astrooda/multiproduct'] = array (
      'title' => 'Administer Astrooda Multi Product',
      'page callback' => 'drupal_get_form',
      'page arguments' => array (
          'astrooda_multiproduct_admin_settings'
      ),
      'description' => 'Edit Astrooda Multi Product settings.',
      'file' => 'astrooda_multiproduct.admin.inc'
  );
  // 'weight' => -10,
  
  return $items;
}

