<?php

/**
 * @file
 * Provides a block displaying prayer times for the visitor's location
 */
function mmoda_jemx_enable() {
  $instrument = mmoda_jemx_instrument_info()['name'];
  _mmodaa_instrument_enable($instrument);
}

function mmoda_jemx_disable() {
  $instrument = mmoda_jemx_instrument_info()['name'];
  _mmodaa_instrument_disable($instrument);
}

function mmoda_jemx_init() {
}

/**
 * Implements hook_help().
 */
function mmoda_jemx_help($path, $arg) {
  $output = '';
  switch ($path) {
    case 'admin/help#mmoda_jemx' :
      $output = '<p>';
      $output .= t ( "MMODA JEM-X." );
      $output .= '</p>';
      break;
  }
  return $output;
}

/**
 * Implementation of hook_permission().
 */

function mmoda_jemx_permission() {
  return array (
      'administer mmoda jemx' => array (
          'description' => t ( 'Administer MMODA JEM-X' ),
          'title' => t ( 'Administer MMODA JEM-X' ),
          'restrict access' => TRUE
      ),
      'access mmoda jemx' => array (
          'description' => t ( 'Access MMODA JEM-X' ),
          'title' => t ( 'Access MMODA JEM-X' ),
          'restrict access' => TRUE
      )
  );
}

/**
 * Menu callback.
 * Prints a listing of active nodes on the site.
 */
function mmoda_jemx_menu() {
  $items = array ();

  $items ['admin/config/mmoda/jemx'] = array (
      'title' => 'Administer MMODA JEM-X',
      'page callback' => 'drupal_get_form',
      'page arguments' => array (
          'mmoda_jemx_admin_settings'
      ),
      'description' => 'Edit MMODA JEM-X settings.',
      'file' => 'mmoda_jemx.admin.inc'
  );
  // 'weight' => -10,

  return $items;
}

